export interface RouteEntry {
  path: string;
  title: string;
  description: string;
  parentRoute?: string;
  theme: string;
  imageAssets: string[];
}

export const ROUTE_MANIFEST: RouteEntry[] = [
  {
    path: '/',
    title: '首页 Portal',
    description: 'Aurora Atlas 门户，六个世界入口的神经连接起点',
    theme: 'default',
    imageAssets: [
      '/1.jpg', '/1-generated.png', '/2.jpg', '/2-time-nodes.png',
      '/3.jpg', '/3-generated.png', '/2-generated.png',
    ],
  },
  {
    path: '/world/overview',
    title: '世界概览',
    description: '世界观总览与宏观数据',
    parentRoute: '/world',
    theme: 'world',
    imageAssets: ['/world-overview-1.png', '/world-overview-2.png'],
  },
  {
    path: '/world/qet',
    title: 'QET 选拔',
    description: 'QET 精英选拔制度说明',
    parentRoute: '/world',
    theme: 'world',
    imageAssets: ['/qet-card.jpg'],
  },
  {
    path: '/world/timeline',
    title: '编年史',
    description: '世界时间线与历史事件',
    parentRoute: '/world',
    theme: 'world',
    imageAssets: ['/timeline-1.png', '/timeline-2.png', '/timeline-3.png', '/timeline-4.png'],
  },
  {
    path: '/world/organizations',
    title: '组织机构',
    description: '哲华学校、因派、德澜思拓、心界等组织',
    parentRoute: '/world',
    theme: 'world',
    imageAssets: [
      '/org-zhihua.jpg', '/icons/org-zhihua.png',
      '/org-impact.jpg', '/icons/org-impact.png',
      '/org-delan.jpg', '/icons/org-delan.png',
      '/org-xinjie.jpg', '/icons/org-xinjie.png',
    ],
  },
  {
    path: '/world/settings',
    title: '世界设定',
    description: '详细的世界设定与规则',
    parentRoute: '/world',
    theme: 'world',
    imageAssets: ['/4d-test-banner.jpg'],
  },
  {
    path: '/world/dictionary',
    title: '词典与诗歌',
    description: '自创语言对照词典',
    parentRoute: '/world',
    theme: 'world',
    imageAssets: [],
  },
  {
    path: '/world/prime-focus',
    title: '未来线',
    description: '未来时间线与关键事件',
    parentRoute: '/world',
    theme: 'world',
    imageAssets: ['/story-prime-focus.jpg', '/story-fill-ocean.jpg', '/story-damocles-exam.jpg'],
  },
  {
    path: '/world/pacific-islands',
    title: '西太平洋诸岛国',
    description: '太平洋岛国设定',
    parentRoute: '/world',
    theme: 'world',
    imageAssets: [],
  },
  {
    path: '/characters/all',
    title: '全部角色',
    description: '全部角色档案（37 个意识体）',
    parentRoute: '/characters',
    theme: 'characters',
    imageAssets: [
      '/characters/miia-generated.png',
      '/characters/mia-generated.png',
      '/characters/miya-generated.png',
      '/characters/amiya-generated.png',
      '/characters/miacubic-generated.png',
      '/characters/lila-generated.png',
      '/characters/changfeng-generated.jpg',
      '/characters/chuxia-generated.jpg',
      '/characters/xiaoman-generated.jpg',
      '/characters/xiaohe-generated.jpg',
      '/characters/xiaogu-generated.jpg',
      '/characters/miaowu-generated.jpg',
      '/characters/xiulan-generated.jpg',
      '/characters/zhouji-generated.jpg',
      '/characters/delivery-rider-generated.jpg',
      '/characters/mxy.jpg',
      '/characters/nimfa.jpg',
      '/characters/nihilib.jpg',
      '/characters/miku.jpg',
      '/characters/qicheng.jpg',
      '/characters/haruka.jpg',
      '/characters/linqian.jpg',
      '/characters/ifchan.jpg',
      '/characters/hamster.jpg',
      '/characters/linshen.jpg',
      '/characters/zhaozhao.jpg',
      '/characters/mowen.jpg',
      '/characters/mimi.jpg',
      '/characters/linear.jpg',
      '/characters/dora.jpg',
      '/characters/cola.jpg',
      '/characters/mao.jpg',
      '/characters/eirene.jpg',
      '/characters/damocles.jpg',
      '/characters/alice-wonderland.jpg',
      '/characters/alice-card.jpg',
      '/characters/linkmo.jpg',
      '/characters/quartus.jpg',
      '/characters/zero.jpg',
    ],
  },
  {
    path: '/characters/mia-family',
    title: 'M/I/A 家族',
    description: 'M/I/A 家族角色筛选',
    parentRoute: '/characters',
    theme: 'characters',
    imageAssets: [],
  },
  {
    path: '/characters/zhehua',
    title: '哲华系',
    description: '哲华学校阵营角色筛选',
    parentRoute: '/characters',
    theme: 'characters',
    imageAssets: [],
  },
  {
    path: '/characters/yin',
    title: '因派系',
    description: '因派阵营角色筛选',
    parentRoute: '/characters',
    theme: 'characters',
    imageAssets: [],
  },
  {
    path: '/characters/delansi',
    title: '德澜思拓',
    description: '德澜思拓阵营角色筛选',
    parentRoute: '/characters',
    theme: 'characters',
    imageAssets: [],
  },
  {
    path: '/characters/grownup-country',
    title: '大人国篇',
    description: '大人国篇角色筛选',
    parentRoute: '/characters',
    theme: 'characters',
    imageAssets: [],
  },
  {
    path: '/characters/other',
    title: '其他',
    description: '其他角色筛选',
    parentRoute: '/characters',
    theme: 'characters',
    imageAssets: [],
  },
  {
    path: '/characters/:id',
    title: '角色详情',
    description: '单个角色详细信息页（38 个角色动态路由）',
    parentRoute: '/characters',
    theme: 'characters',
    imageAssets: [],
  },
  {
    path: '/stories',
    title: '故事目录',
    description: '全部叙事宇宙索引',
    theme: 'stories',
    imageAssets: [
      '/story-mia-world-1.jpg',
      '/story-fox-penguin.jpg',
      '/story-agi-land.jpg',
      '/story-zhenhai-refining.png',
      '/story-miia-dream-generated.png',
    ],
  },
  {
    path: '/stories/mia-world',
    title: "M/I/As' World",
    description: '背景设定故事，含 3 个章节',
    parentRoute: '/stories',
    theme: 'story-mia',
    imageAssets: [
      '/story-mia-world-1.jpg', '/story-mia-world-2.jpg', '/story-mia-world-3.jpg',
    ],
  },
  {
    path: '/stories/fox-penguin',
    title: '狐狸与企鹅的彩虹泡泡海',
    description: '9 章童话故事',
    parentRoute: '/stories',
    theme: 'story-ocean',
    imageAssets: [
      '/fox-penguin-ch01.png', '/fox-penguin-ch02.png', '/fox-penguin-ch03.png',
      '/fox-penguin-ch04.png', '/fox-penguin-ch05.png', '/fox-penguin-ch06.png',
      '/fox-penguin-ch07.png', '/fox-penguin-ch08.png', '/fox-penguin-ch09.png',
    ],
  },
  {
    path: '/stories/zhenhai-refining',
    title: '镇海炼化录',
    description: '东海之滨的炼器宗门，含 8 个章节',
    parentRoute: '/stories',
    theme: 'story-zhenhai',
    imageAssets: [
      '/story-zhenhai-refining.png', '/story-zhenhai-wash.jpg',
      '/story-zhenhai-fire-refining.jpg', '/story-zhenhai-rebirth.jpg',
      '/story-zhenhai-conditioning.jpg', '/story-zhenhai-inspection.jpg',
      '/story-zhenhai-sealing-transit.jpg', '/story-zhenhai-mortal-epilogue.jpg',
    ],
  },
  {
    path: '/stories/agi-land',
    title: 'AGI 应许之地',
    description: '咪呀的愿景 — AGI 托底的私人游乐场',
    parentRoute: '/stories',
    theme: 'story-agi',
    imageAssets: [],
  },
  {
    path: '/stories/little-girl-in-giant-country',
    title: '大人国的小女孩',
    description: '第一卷 · 小满来到这里的三十天，65 章节',
    parentRoute: '/stories',
    theme: 'story-giant',
    imageAssets: [
      '/story-giant-part-1.png', '/story-giant-part-2.png', '/story-giant-part-3.png',
      '/story-giant-part-4.png', '/story-giant-part-5.png', '/story-giant-part-6.png',
      '/story-giant-part-7.png', '/story-giant-part-8.png',
      '/story-miia-dream-generated.png',
    ],
  },
  {
    path: '/miia/world',
    title: '咪呀的世界',
    description: '内心独白与世界观碎片',
    parentRoute: '/miia',
    theme: 'miia',
    imageAssets: ['/story-miia-dream.jpg', '/story-agi-pyramid.jpg', '/story-lila.jpg'],
  },
  {
    path: '/miia/math',
    title: '数学笔记',
    description: '咪呀的数学遐想与笔记',
    parentRoute: '/miia',
    theme: 'miia',
    imageAssets: [],
  },
  {
    path: '/miia/poems',
    title: '诗歌碎片',
    description: '诗歌与文学碎片集合',
    parentRoute: '/miia',
    theme: 'miia',
    imageAssets: [
      '/story-paradigm.jpg', '/story-code-poem.jpg', '/story-bad-rabbit.jpg',
      '/story-sheep-song.jpg', '/story-overdose-icu.jpg', '/story-xishou-nianshou.jpg',
      '/story-3-people-world.jpg',
    ],
  },
  {
    path: '/math/fsiii',
    title: 'FSIII 排名',
    description: 'Full Scale Intrinsic Intelligence Index 排名',
    parentRoute: '/math',
    theme: 'math',
    imageAssets: [],
  },
  {
    path: '/math/fla',
    title: 'PEMS-L FLA',
    description: 'PEMS-L FLA 模型',
    parentRoute: '/math',
    theme: 'math',
    imageAssets: [],
  },
  {
    path: '/math/height-weight',
    title: '身高体重模型',
    description: '角色身高体重数据模型',
    parentRoute: '/math',
    theme: 'math',
    imageAssets: [],
  },
  {
    path: '/playground/games',
    title: '可玩游戏',
    description: '游戏列表入口',
    parentRoute: '/playground',
    theme: 'playground',
    imageAssets: [],
  },
  {
    path: '/playground/rules',
    title: '规则说明',
    description: '游戏规则文档',
    parentRoute: '/playground',
    theme: 'playground',
    imageAssets: [],
  },
  {
    path: '/playground/scratch',
    title: 'Scratch 小游戏',
    description: 'Scratch 小游戏集合',
    parentRoute: '/playground',
    theme: 'playground',
    imageAssets: [],
  },
  {
    path: '/api',
    title: 'API 目录',
    description: 'API 文档与接口目录',
    theme: 'api',
    imageAssets: [],
  },
  {
    path: '/chat',
    title: '星海甜梦舱',
    description: 'Chat 聊天界面',
    theme: 'default',
    imageAssets: ['/pets/poffy.png'],
  },
  {
    path: '/sweetdream',
    title: 'SweetDream Chat',
    description: '甜梦聊天界面（独立路由）',
    theme: 'default',
    imageAssets: ['/pets/poffy.png'],
  },
  {
    path: '/*',
    title: '404 页面',
    description: '未找到页面',
    theme: 'default',
    imageAssets: [],
  },
];
