// English mirror of ./formal-a.v1 — same ids, English text.
import { definePublicQuestion } from './helpers.ts';
import type { NctbPublicQuestion } from '../types.ts';

const bankId = 'formal-a-v1' as const;

export const FORMAL_A_V1_QUESTIONS_EN: readonly NctbPublicQuestion[] = [
  definePublicQuestion({
    id: 'formal-a-v1-pattern-01', bankId, dimensionId: 'pattern', difficulty: 2, family: 'alternating-operator',
    stimulus: '◇ ◆ ◆   ◇ ◆ ◆   ?',
    prompt: 'Which symbol should come at the question mark?',
    options: ['◆', '◇', '○', '■'],
    profile: { reasoningSteps: 1, workingMemoryLoad: 2, distractorSimilarity: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-pattern-02', bankId, dimensionId: 'pattern', difficulty: 3, family: 'analogy-transform',
    stimulus: 'Example: [△ ○ ■] → [□ ● ▲]\nTo process: [● □ ◇]',
    prompt: 'The example uses both "reverse order" and "hollow/solid swap". What is the result of the sequence to process?',
    options: ['◇ □ ●', '◆ □ ○', '○ ■ ◆', '◆ ■ ○'],
    profile: { reasoningSteps: 2, workingMemoryLoad: 3, abstraction: 3, ruleSwitches: 1 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-pattern-03', bankId, dimensionId: 'pattern', difficulty: 5, family: 'recursive-pattern',
    stimulus: 'Row 1: ● ○ ● ○\nRow 2: ● ● ○ ○\nRule: in the next row, each cell is ● when the two previous rows differ in that cell, ○ when they match.',
    prompt: 'Apply the rule twice in a row: what is row 4?',
    options: ['○ ● ● ○', '● ● ● ●', '● ○ ● ○', '○ ○ ○ ○'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 4, abstraction: 5, distractorSimilarity: 4 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-memory-01', bankId, dimensionId: 'memory', difficulty: 2, family: 'binding-memory', kind: 'memory',
    stimulus: 'K—star   M—bridge   R—leaf   T—clock', revealMs: 4_000,
    prompt: 'Which letter was paired with "bridge" just now?',
    options: ['M', 'R', 'K', 'T'],
    profile: { reasoningSteps: 0, workingMemoryLoad: 3, distractorSimilarity: 3 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-memory-02', bankId, dimensionId: 'memory', difficulty: 4, family: 'memory-updating', kind: 'memory',
    stimulus: 'Start: red–blue–gray–green\nDelete item 2; move the last item to the front; add "white" at the end.', revealMs: 5_400,
    prompt: 'What is the order after the operations?',
    options: ['green–red–blue–white', 'red–gray–green–white', 'green–red–gray–white', 'white–green–red–gray'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 5, distractorSimilarity: 4, ruleSwitches: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-memory-03', bankId, dimensionId: 'memory', difficulty: 5, family: 'interference-memory', kind: 'memory',
    stimulus: 'Target: lake—4, tower—7, pine—2\nInterference: lake—7, tower—2, pine—4', revealMs: 5_800,
    prompt: 'In the target list, what numbers are "tower" and "pine" paired with?',
    options: ['tower—2, pine—4', 'tower—7, pine—2', 'tower—4, pine—7', 'tower—7, pine—4'],
    profile: { reasoningSteps: 0, workingMemoryLoad: 5, distractorSimilarity: 5, stimulusComplexity: 5 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-space-01', bankId, dimensionId: 'space', difficulty: 2, family: 'mental-rotation',
    stimulus: 'Three occupied cells at (0,0), (1,0), (1,1). Rotate 90° clockwise around the origin.',
    prompt: 'Which set of coordinates results from the rotation?',
    options: ['(0,0)、(0,-1)、(1,-1)', '(0,0)、(-1,0)、(-1,-1)', '(0,0)、(0,1)、(-1,1)', '(0,0)、(1,0)、(1,-1)'],
    profile: { reasoningSteps: 2, workingMemoryLoad: 2, abstraction: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-space-02', bankId, dimensionId: 'space', difficulty: 4, family: 'path-integration',
    stimulus: 'Facing north, advance 2 cells from the start; turn right and advance 1; turn 180° in place, then advance 1.',
    prompt: 'Where is the endpoint relative to the start?',
    options: ['1 cell due north', '2 cells due east', '2 cells due north', 'back at the start'],
    profile: { reasoningSteps: 4, workingMemoryLoad: 4, distractorSimilarity: 4, ruleSwitches: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-space-03', bankId, dimensionId: 'space', difficulty: 5, family: 'paper-folding',
    stimulus: 'A sheet of paper, 2 rows × 4 columns. First fold the left half over the right along the middle vertical line, then fold the bottom half up along the middle horizontal line. Punch a hole in the top-right corner of the folded paper.',
    prompt: 'After fully unfolding, where does the hole appear?',
    options: ['only at the original top-right corner', 'the top corners of both sides', 'the right two corners (top and bottom)', 'all four corners of the original paper'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 4, abstraction: 4, stimulusComplexity: 4 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-quantity-01', bankId, dimensionId: 'quantity', difficulty: 2, family: 'proportional-comparison',
    prompt: 'Machine A finishes 12 items in 3 minutes; machine B finishes 18 items in 6 minutes. At constant speed, which completes more per minute?',
    options: ['Machine A', 'Machine B', 'The same', 'Not enough information'],
    profile: { reasoningSteps: 2, workingMemoryLoad: 2, distractorSimilarity: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-quantity-02', bankId, dimensionId: 'quantity', difficulty: 4, family: 'relative-quantity',
    prompt: 'A is 20% less than B, and C is 25% more than A. How does C compare with B?',
    options: ['C is 5% more than B', 'C is 5% less than B', 'C equals B', 'Cannot compare'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 3, distractorSimilarity: 4, abstraction: 3 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-quantity-03', bankId, dimensionId: 'quantity', difficulty: 5, family: 'quantitative-transform',
    stimulus: 'Exchange rules: 3 blue tokens = 2 gold tokens; 1 gold token = 4 green tokens.',
    prompt: '9 blue tokens equal how many green tokens?',
    options: ['18', '24', '12', '36'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 4, abstraction: 4, distractorSimilarity: 4 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-language-01', bankId, dimensionId: 'language', difficulty: 2, family: 'conditional-language',
    prompt: 'If an archive is encrypted, opening it requires a key. Opening this archive did not require a key. What follows?',
    options: ['The archive is definitely public', 'The archive is not encrypted', 'The key is lost', 'The archive is empty'],
    profile: { reasoningSteps: 2, abstraction: 2, distractorSimilarity: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-language-02', bankId, dimensionId: 'language', difficulty: 4, family: 'quantifier-scope',
    prompt: '"Not everyone who passed the initial check submitted a report." What must this sentence mean?',
    options: ['No one submitted a report', 'No one passed the initial check', 'Exactly one person passed the initial check', 'At least one person who passed the initial check did not submit a report'],
    profile: { reasoningSteps: 2, workingMemoryLoad: 3, abstraction: 4, distractorSimilarity: 4 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-language-03', bankId, dimensionId: 'language', difficulty: 5, family: 'instruction-comprehension',
    stimulus: 'Rule 1: Unless the red light is off, do not open the door.\nRule 2: Only when the door is locked does the red light go off.\nCurrent state: the red light is off.',
    prompt: 'Based only on the rules, which must hold?',
    options: ['The door can definitely be opened now', 'The door has been opened', 'The door is locked', 'The red light will not come on again'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 4, abstraction: 5, distractorSimilarity: 5 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-attention-01', bankId, dimensionId: 'attention', difficulty: 2, family: 'selective-search',
    stimulus: 'Response rule: select only "solid triangle + odd number"; suppress any item with a slash /.  A ▲5   B △5   C ▲4   D ▲7/',
    prompt: 'Which item is the only one to respond to?',
    options: ['A', 'B', 'C', 'D'],
    profile: { reasoningSteps: 0, workingMemoryLoad: 1, distractorSimilarity: 3, stimulusComplexity: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-attention-02', bankId, dimensionId: 'attention', difficulty: 4, family: 'rule-switching',
    stimulus: 'Rule: L takes the smaller number, R takes the larger number.\nL 3 8 | R 2 7 | L 4 9 | R 6 5 | L 8 1',
    prompt: 'Among the numbers chosen per row\'s rule, how many are even?',
    options: ['2', '3', '1', '4'],
    profile: { reasoningSteps: 1, workingMemoryLoad: 3, distractorSimilarity: 4, ruleSwitches: 4, stimulusComplexity: 4 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-attention-03', bankId, dimensionId: 'attention', difficulty: 3, family: 'flanker-interference',
    stimulus: 'Rule: ignore the side arrows, respond only to the central arrow; whole rows marked × get no response.\nA ＞＞＜＞＞   B ＜＜＞＜＜   C ＞＞＜＞＞×   D ＜＜＞＜＜×',
    prompt: 'Which row calls for a "move left" response?',
    options: ['A', 'B', 'C', 'D'],
    profile: { reasoningSteps: 0, workingMemoryLoad: 2, distractorSimilarity: 4, ruleSwitches: 1, stimulusComplexity: 3 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-speed-01', bankId, dimensionId: 'speed', difficulty: 1, family: 'rapid-classification',
    stimulus: '2A   7B   4C   9D   6E',
    prompt: 'How many items start with an even digit?',
    options: ['2', '3', '4', '1'],
    profile: { reasoningSteps: 0, workingMemoryLoad: 1, distractorSimilarity: 2, stimulusComplexity: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-speed-02', bankId, dimensionId: 'speed', difficulty: 3, family: 'visual-comparison',
    stimulus: 'Target: Q7M2K',
    prompt: 'Which item is exactly identical to the target?',
    options: ['Q7N2K', 'Q7MZK', 'Q7M2K', 'O7M2K'],
    profile: { reasoningSteps: 0, workingMemoryLoad: 1, distractorSimilarity: 5, stimulusComplexity: 3 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-speed-03', bankId, dimensionId: 'speed', difficulty: 4, family: 'feature-scan',
    stimulus: 'A7A   B8C   D2D   E3F   G5G   H6J',
    prompt: 'How many items have identical first and last characters?',
    options: ['2', '3', '4', '1'],
    profile: { reasoningSteps: 0, workingMemoryLoad: 2, distractorSimilarity: 5, stimulusComplexity: 5 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-causality-01', bankId, dimensionId: 'causality', difficulty: 2, family: 'causal-graph',
    stimulus: 'A starts B, and B starts C; there are no other paths. In an experiment, start A while blocking B.',
    prompt: 'What is the most reasonable prediction about C?',
    options: ['C will definitely start', 'C will not be started by A', 'C will directly start B', 'Cannot tell whether B was blocked'],
    profile: { reasoningSteps: 2, abstraction: 2, stimulusComplexity: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-causality-02', bankId, dimensionId: 'causality', difficulty: 4, family: 'evidence-strength',
    prompt: 'People who use a walking app take fewer sick days, but they are also younger on average. Which new study best tests the app\'s own effect?',
    options: ['Interview only the people with the fewest sick days', 'Compare everyone\'s this year vs. last year', 'Randomly assign eligible people to with/without the app, then compare sick days', 'Enlarge the original observation sample without changing grouping'],
    profile: { reasoningSteps: 2, workingMemoryLoad: 3, abstraction: 4, distractorSimilarity: 4 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-causality-03', bankId, dimensionId: 'causality', difficulty: 5, family: 'necessary-sufficient',
    stimulus: 'Adequate water W is a necessary condition for flowering; when W exists, either strong light L or agent C alone suffices to trigger flowering. The plant has flowered.',
    prompt: 'Which must hold?',
    options: ['L exists', 'C exists', 'Both L and C exist', 'W must exist; neither L nor C can be determined'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 4, abstraction: 5, distractorSimilarity: 5 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-planning-01', bankId, dimensionId: 'planning', difficulty: 2, family: 'constraint-planning',
    prompt: 'Four tasks P, Q, R, S each occupy one slot. P is before R; Q must immediately precede S; Q cannot be first. Which order is valid?',
    options: ['Q–S–P–R', 'P–Q–S–R', 'P–S–Q–R', 'R–P–Q–S'],
    profile: { reasoningSteps: 2, workingMemoryLoad: 3, distractorSimilarity: 3 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-planning-02', bankId, dimensionId: 'planning', difficulty: 4, family: 'resource-planning',
    stimulus: 'A uses the machine for 2 hours; B uses the same machine for 1 hour; C uses no machine but must run for 2 hours after A; D must wait until both B and C finish.',
    prompt: 'Which arrangement lets D start earliest?',
    options: ['The machine does B first, then A, and only then C', 'The machine does A first; after A finishes, the machine does B while C runs', 'A and B use the machine simultaneously', 'Do C first, then A and B'],
    profile: { reasoningSteps: 4, workingMemoryLoad: 4, abstraction: 3, stimulusComplexity: 4 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-planning-03', bankId, dimensionId: 'planning', difficulty: 5, family: 'replanning',
    stimulus: 'Original plan: sample→cool→test→submit. The cooling equipment fails; slower natural cooling is available. There is also a "check labels" task that must finish before submission but can run in parallel with cooling. The deadline can still be met.',
    prompt: 'What is the most reasonable new plan?',
    options: ['Skip cooling and test directly', 'Wait for equipment repair and pause everything else', 'Cancel testing and submit directly', 'Start natural cooling immediately while checking labels; after cooling, test, then submit'],
    profile: { reasoningSteps: 4, workingMemoryLoad: 5, distractorSimilarity: 4, abstraction: 4, ruleSwitches: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-transfer-01', bankId, dimensionId: 'transfer', difficulty: 2, family: 'structural-analogy',
    prompt: 'In the old task, file A depends on B and B depends on A, so the system cannot decide which to process first. In the new task, two processes each require the other to finish first. What is the most relevant diagnosis from the old task?',
    options: ['Too few inputs', 'A circular dependency exists', 'The two surface names differ', 'Both need to be deleted'],
    profile: { reasoningSteps: 2, abstraction: 3, distractorSimilarity: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-transfer-02', bankId, dimensionId: 'transfer', difficulty: 4, family: 'far-transfer',
    prompt: 'In the old scenario, two serial gates have limited capacity, and releasing items in batches based on downstream spare capacity avoids congestion. The new scenario is a two-stage data-processing queue. Which strategy preserves the deep structure?',
    options: ['Keep the upstream sending at full speed continuously', 'Give the first stage prettier labels only', 'Adjust input batches by the second stage\'s processing headroom', 'Randomly drop all data'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 3, abstraction: 5, distractorSimilarity: 4 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-transfer-03', bankId, dimensionId: 'transfer', difficulty: 5, family: 'boundary-aware-transfer',
    stimulus: 'Old task: the hidden amount decreases by a fixed 3 each step, so the first two steps can be extrapolated.\nNew task: the first two steps also decrease by 3, but the material explicitly says "below the threshold, the decrease becomes 1 per step".',
    prompt: 'How should the old strategy be transferred most reasonably?',
    options: ['Always extrapolate by -3', 'Ignore the first-two-step pattern entirely', 'Copy only the old task\'s final value', 'Use the fixed-difference strategy before the threshold, then switch to the new rule after it'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 4, abstraction: 5, ruleSwitches: 2, distractorSimilarity: 5 },
  }),
];
