import { definePublicQuestion } from './helpers.ts';
import type { NctbPublicQuestion } from '../types.ts';

const bankId = 'formal-a-v1' as const;

export const FORMAL_A_V1_QUESTIONS: readonly NctbPublicQuestion[] = [
  definePublicQuestion({
    id: 'formal-a-v1-pattern-01', bankId, dimensionId: 'pattern', difficulty: 2, family: 'alternating-operator',
    stimulus: '◇ ◆ ◆   ◇ ◆ ◆   ?',
    prompt: '问号处应接哪个符号？',
    options: ['◆', '◇', '○', '■'],
    profile: { reasoningSteps: 1, workingMemoryLoad: 2, distractorSimilarity: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-pattern-02', bankId, dimensionId: 'pattern', difficulty: 3, family: 'analogy-transform',
    stimulus: '示例：[△ ○ ■] → [□ ● ▲]\n待处理：[● □ ◇]',
    prompt: '示例同时使用“倒序”和“空实互换”。待处理序列的结果是什么？',
    options: ['◇ □ ●', '◆ □ ○', '○ ■ ◆', '◆ ■ ○'],
    profile: { reasoningSteps: 2, workingMemoryLoad: 3, abstraction: 3, ruleSwitches: 1 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-pattern-03', bankId, dimensionId: 'pattern', difficulty: 5, family: 'recursive-pattern',
    stimulus: '第 1 行：● ○ ● ○\n第 2 行：● ● ○ ○\n规则：下一行每格在前两行该格不同时为 ●，相同时为 ○。',
    prompt: '连续应用规则两次，第 4 行是什么？',
    options: ['○ ● ● ○', '● ● ● ●', '● ○ ● ○', '○ ○ ○ ○'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 4, abstraction: 5, distractorSimilarity: 4 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-memory-01', bankId, dimensionId: 'memory', difficulty: 2, family: 'binding-memory', kind: 'memory',
    stimulus: 'K—星   M—桥   R—叶   T—钟', revealMs: 4_000,
    prompt: '刚才与“桥”配对的字母是什么？',
    options: ['M', 'R', 'K', 'T'],
    profile: { reasoningSteps: 0, workingMemoryLoad: 3, distractorSimilarity: 3 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-memory-02', bankId, dimensionId: 'memory', difficulty: 4, family: 'memory-updating', kind: 'memory',
    stimulus: '起始：红–蓝–灰–绿\n删除第 2 项；把末项移到首位；末尾加入“白”。', revealMs: 5_400,
    prompt: '操作后的顺序是什么？',
    options: ['绿–红–蓝–白', '红–灰–绿–白', '绿–红–灰–白', '白–绿–红–灰'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 5, distractorSimilarity: 4, ruleSwitches: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-memory-03', bankId, dimensionId: 'memory', difficulty: 5, family: 'interference-memory', kind: 'memory',
    stimulus: '目标：湖—4，塔—7，松—2\n干扰：湖—7，塔—2，松—4', revealMs: 5_800,
    prompt: '目标列表中，“塔”和“松”分别配对什么数字？',
    options: ['塔—2，松—4', '塔—7，松—2', '塔—4，松—7', '塔—7，松—4'],
    profile: { reasoningSteps: 0, workingMemoryLoad: 5, distractorSimilarity: 5, stimulusComplexity: 5 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-space-01', bankId, dimensionId: 'space', difficulty: 2, family: 'mental-rotation',
    stimulus: '三个占用格坐标为 (0,0)、(1,0)、(1,1)。绕原点顺时针旋转 90°。',
    prompt: '旋转后的三个坐标是哪一组？',
    options: ['(0,0)、(0,-1)、(1,-1)', '(0,0)、(-1,0)、(-1,-1)', '(0,0)、(0,1)、(-1,1)', '(0,0)、(1,0)、(1,-1)'],
    profile: { reasoningSteps: 2, workingMemoryLoad: 2, abstraction: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-space-02', bankId, dimensionId: 'space', difficulty: 4, family: 'path-integration',
    stimulus: '面向北，从起点前进 2 格；右转后前进 1 格；原地转身 180°，再前进 1 格。',
    prompt: '终点相对起点在哪里？',
    options: ['正北 1 格', '正东 2 格', '正北 2 格', '回到起点'],
    profile: { reasoningSteps: 4, workingMemoryLoad: 4, distractorSimilarity: 4, ruleSwitches: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-space-03', bankId, dimensionId: 'space', difficulty: 5, family: 'paper-folding',
    stimulus: '一张 2 行×4 列的纸，先沿中间竖线把左半向右折，再沿中间横线把下半向上折。此时在折后右上角打孔。',
    prompt: '完全展开后，孔出现在哪里？',
    options: ['只在原纸右上角', '左右两边的上角', '右侧上下两个角', '原纸四个角'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 4, abstraction: 4, stimulusComplexity: 4 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-quantity-01', bankId, dimensionId: 'quantity', difficulty: 2, family: 'proportional-comparison',
    prompt: '机器 A 在 3 分钟完成 12 件，机器 B 在 6 分钟完成 18 件。若速度不变，哪台每分钟完成得更多？',
    options: ['机器 A', '机器 B', '两台相同', '信息不足'],
    profile: { reasoningSteps: 2, workingMemoryLoad: 2, distractorSimilarity: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-quantity-02', bankId, dimensionId: 'quantity', difficulty: 4, family: 'relative-quantity',
    prompt: 'A 比 B 少 20%，C 又比 A 多 25%。C 与 B 相比怎样？',
    options: ['C 比 B 多 5%', 'C 比 B 少 5%', 'C 与 B 相等', '无法比较'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 3, distractorSimilarity: 4, abstraction: 3 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-quantity-03', bankId, dimensionId: 'quantity', difficulty: 5, family: 'quantitative-transform',
    stimulus: '交换规则：3 个蓝筹 = 2 个金筹；1 个金筹 = 4 个绿筹。',
    prompt: '9 个蓝筹与多少个绿筹等值？',
    options: ['18', '24', '12', '36'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 4, abstraction: 4, distractorSimilarity: 4 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-language-01', bankId, dimensionId: 'language', difficulty: 2, family: 'conditional-language',
    prompt: '若档案已加密，则打开它需要钥匙。现在打开这份档案不需要钥匙。哪项可以推出？',
    options: ['档案一定公开', '档案未加密', '钥匙已经丢失', '档案内容为空'],
    profile: { reasoningSteps: 2, abstraction: 2, distractorSimilarity: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-language-02', bankId, dimensionId: 'language', difficulty: 4, family: 'quantifier-scope',
    prompt: '“并非所有通过初检的人都提交了报告。”这句话必然表示什么？',
    options: ['没有人提交报告', '所有人都没通过初检', '只有一人通过初检', '至少一名通过初检的人没有提交报告'],
    profile: { reasoningSteps: 2, workingMemoryLoad: 3, abstraction: 4, distractorSimilarity: 4 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-language-03', bankId, dimensionId: 'language', difficulty: 5, family: 'instruction-comprehension',
    stimulus: '规则 1：除非红灯熄灭，否则不要开门。\n规则 2：只有门已锁定，红灯才会熄灭。\n现状：红灯已熄灭。',
    prompt: '只根据规则，哪项必然成立？',
    options: ['门现在一定可以打开', '门已经打开', '门已锁定', '红灯不会再次亮起'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 4, abstraction: 5, distractorSimilarity: 5 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-attention-01', bankId, dimensionId: 'attention', difficulty: 2, family: 'selective-search',
    stimulus: '响应规则：只选“实心三角 + 奇数”；带斜线 / 的项目一律抑制。\nA ▲5   B △5   C ▲4   D ▲7/',
    prompt: '唯一应该响应的是哪个项目？',
    options: ['A', 'B', 'C', 'D'],
    profile: { reasoningSteps: 0, workingMemoryLoad: 1, distractorSimilarity: 3, stimulusComplexity: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-attention-02', bankId, dimensionId: 'attention', difficulty: 4, family: 'rule-switching',
    stimulus: '规则：L 取较小数字，R 取较大数字。\nL 3 8 | R 2 7 | L 4 9 | R 6 5 | L 8 1',
    prompt: '按每行规则选出的数字中，偶数有几个？',
    options: ['2', '3', '1', '4'],
    profile: { reasoningSteps: 1, workingMemoryLoad: 3, distractorSimilarity: 4, ruleSwitches: 4, stimulusComplexity: 4 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-attention-03', bankId, dimensionId: 'attention', difficulty: 3, family: 'flanker-interference',
    stimulus: '规则：忽略两侧箭头，只按中央箭头反应；带 × 的整行不反应。\nA ＞＞＜＞＞   B ＜＜＞＜＜   C ＞＞＜＞＞×   D ＜＜＞＜＜×',
    prompt: '哪一行要求做“向左”反应？',
    options: ['A', 'B', 'C', 'D'],
    profile: { reasoningSteps: 0, workingMemoryLoad: 2, distractorSimilarity: 4, ruleSwitches: 1, stimulusComplexity: 3 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-speed-01', bankId, dimensionId: 'speed', difficulty: 1, family: 'rapid-classification',
    stimulus: '2A   7B   4C   9D   6E',
    prompt: '以“偶数开头”的项目有几组？',
    options: ['2', '3', '4', '1'],
    profile: { reasoningSteps: 0, workingMemoryLoad: 1, distractorSimilarity: 2, stimulusComplexity: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-speed-02', bankId, dimensionId: 'speed', difficulty: 3, family: 'visual-comparison',
    stimulus: '目标：Q7M2K',
    prompt: '哪一项与目标完全相同？',
    options: ['Q7N2K', 'Q7MZK', 'Q7M2K', 'O7M2K'],
    profile: { reasoningSteps: 0, workingMemoryLoad: 1, distractorSimilarity: 5, stimulusComplexity: 3 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-speed-03', bankId, dimensionId: 'speed', difficulty: 4, family: 'feature-scan',
    stimulus: 'A7A   B8C   D2D   E3F   G5G   H6J',
    prompt: '首尾字符相同的项目有几组？',
    options: ['2', '3', '4', '1'],
    profile: { reasoningSteps: 0, workingMemoryLoad: 2, distractorSimilarity: 5, stimulusComplexity: 5 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-causality-01', bankId, dimensionId: 'causality', difficulty: 2, family: 'causal-graph',
    stimulus: 'A 会启动 B，B 会启动 C；没有其他通路。实验中启动 A，同时阻断 B。',
    prompt: '对 C 最合理的预测是什么？',
    options: ['C 一定启动', 'C 不会由 A 启动', 'C 会直接启动 B', '无法判断 B 是否被阻断'],
    profile: { reasoningSteps: 2, abstraction: 2, stimulusComplexity: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-causality-02', bankId, dimensionId: 'causality', difficulty: 4, family: 'evidence-strength',
    prompt: '使用步行应用的人病假更少，但他们平均更年轻。哪项新研究最能检验应用本身的作用？',
    options: ['只采访病假最少的人', '比较今年与去年所有人', '随机把符合条件的人分配为有无应用，再比较病假', '扩大原观察样本但不改变分组方式'],
    profile: { reasoningSteps: 2, workingMemoryLoad: 3, abstraction: 4, distractorSimilarity: 4 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-causality-03', bankId, dimensionId: 'causality', difficulty: 5, family: 'necessary-sufficient',
    stimulus: '充足水分 W 是开花的必要条件；在 W 存在时，强光 L 或药剂 C 任一个都足以引发开花。现在植物开花了。',
    prompt: '哪项必然成立？',
    options: ['L 存在', 'C 存在', 'L 与 C 都存在', 'W 必然存在；L 与 C 均无法确定'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 4, abstraction: 5, distractorSimilarity: 5 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-planning-01', bankId, dimensionId: 'planning', difficulty: 2, family: 'constraint-planning',
    prompt: '四项任务 P、Q、R、S 各占一个位置。P 在 R 前；Q 必须紧接在 S 前；Q 不能排第一。哪种顺序有效？',
    options: ['Q–S–P–R', 'P–Q–S–R', 'P–S–Q–R', 'R–P–Q–S'],
    profile: { reasoningSteps: 2, workingMemoryLoad: 3, distractorSimilarity: 3 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-planning-02', bankId, dimensionId: 'planning', difficulty: 4, family: 'resource-planning',
    stimulus: 'A 用机器 2 小时；B 用同一机器 1 小时；C 不用机器但必须在 A 后进行 2 小时；D 必须等 B、C 都完成。',
    prompt: '哪种安排最早让 D 开始？',
    options: ['机器先做 B 再做 A，之后才做 C', '机器先做 A；A 完成后机器做 B，同时进行 C', 'A 与 B 同时使用机器', '先做 C，再做 A 与 B'],
    profile: { reasoningSteps: 4, workingMemoryLoad: 4, abstraction: 3, stimulusComplexity: 4 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-planning-03', bankId, dimensionId: 'planning', difficulty: 5, family: 'replanning',
    stimulus: '原计划：取样→冷却→检测→提交。冷却设备失效；可用较慢的自然冷却。另有“校对标签”任务，必须在提交前完成，但可与冷却并行。截止时间仍可满足。',
    prompt: '最合理的新计划是什么？',
    options: ['跳过冷却直接检测', '等待设备维修，其他任务全部暂停', '取消检测并直接提交', '立刻自然冷却，同时校对标签；冷却后检测，再提交'],
    profile: { reasoningSteps: 4, workingMemoryLoad: 5, distractorSimilarity: 4, abstraction: 4, ruleSwitches: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-transfer-01', bankId, dimensionId: 'transfer', difficulty: 2, family: 'structural-analogy',
    prompt: '旧任务中，文件 A 依赖 B、B 又依赖 A，系统因此无法确定先处理谁。新任务中，两道工序互相要求对方先完成。旧任务最相关的诊断是什么？',
    options: ['输入数量太少', '存在循环依赖', '两项表面名称不同', '需要把两项同时删除'],
    profile: { reasoningSteps: 2, abstraction: 3, distractorSimilarity: 2 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-transfer-02', bankId, dimensionId: 'transfer', difficulty: 4, family: 'far-transfer',
    prompt: '旧场景中，两道串联闸门容量有限，依据下游空闲程度分批放行能避免堵塞。新场景是两级数据处理队列。哪种策略保留了深层结构？',
    options: ['让上游持续满速发送', '只给第一级更好看的标签', '按第二级的处理余量调节输入批次', '随机丢弃所有数据'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 3, abstraction: 5, distractorSimilarity: 4 },
  }),
  definePublicQuestion({
    id: 'formal-a-v1-transfer-03', bankId, dimensionId: 'transfer', difficulty: 5, family: 'boundary-aware-transfer',
    stimulus: '旧任务：隐藏量每步固定减少 3，因此可用前两步外推。\n新任务：前两步也各减少 3，但材料明确说明“低于阈值后改为每步减少 1”。',
    prompt: '怎样迁移旧策略最合理？',
    options: ['始终按减少 3 外推', '完全忽略前两步规律', '只复制旧任务的最终数值', '阈值前沿用固定差策略，阈值后改用新规则'],
    profile: { reasoningSteps: 3, workingMemoryLoad: 4, abstraction: 5, ruleSwitches: 2, distractorSimilarity: 5 },
  }),
];
