// English mirror of ./specs/index — same ids, English text.
import type { DimensionSpec } from '../types.ts';

export const DIMENSION_SPECS_EN: readonly DimensionSpec[] = [
  {
    id: 'pattern',
    construct: 'Extracting, combining and extending relation rules from non-verbal material.',
    measures: ['relation abstraction', 'multi-rule induction', 'period discovery', 'recursive structure', 'analogy structure', 'rule-boundary recognition'],
    shouldNotMeasure: ['school math proficiency', 'single arithmetic or geometric sequences', 'trivia', 'large-number mental arithmetic'],
    itemFamilies: ['matrix-relation', 'recursive-pattern', 'periodic-overlay', 'analogy-transform', 'rule-classification', 'alternating-operator'],
    difficultyModel: ['number of rules maintained simultaneously', 'rule abstraction level', 'reasoning steps', 'similar distractors', 'exceptions or boundary conditions'],
  },
  {
    id: 'memory',
    construct: 'Briefly holding information and updating, binding, suppressing or reordering it while held.',
    measures: ['forward maintenance', 'backward maintenance', 'reordering', 'item-position binding', 'updating', 'interference resistance', 'n-back-style matching', 'sequence transformation'],
    shouldNotMeasure: ['long-term knowledge', 'relying only on pen-and-paper records', 'all items using reversed digits', 'complex reasoning'],
    itemFamilies: ['forward-span', 'backward-span', 'ordered-recall', 'binding-memory', 'memory-updating', 'interference-memory', 'n-back-match', 'sequence-transformation'],
    difficultyModel: ['item count', 'item similarity', 'number of operations', 'interference strength', 'maintenance interval', 'number of binding relations'],
  },
  {
    id: 'space',
    construct: 'Maintaining and transforming spatial relations when viewpoint or objects change.',
    measures: ['mental rotation', 'folding/unfolding', 'spatial relations', 'path integration', 'viewpoint transformation', 'object transformation', 'grid movement'],
    shouldNotMeasure: ['only single-step cardinal rotations', 'geographic knowledge', 'professional drafting terms', 'pure verbal logic'],
    itemFamilies: ['mental-rotation', 'paper-folding', 'spatial-relation', 'path-integration', 'viewpoint-transform', 'object-transform', 'grid-movement'],
    difficultyModel: ['number of rotation axes', 'transformation steps', 'occlusion or fold layers', 'viewpoint switches', 'spatial distractor similarity'],
  },
  {
    id: 'quantity',
    construct: 'Understanding proportions, relative relations and post-operation changes between quantities.',
    measures: ['quantity relations', 'proportion', 'estimation', 'relative quantity', 'arithmetic modeling', 'quantity transformation', 'resource balancing'],
    shouldNotMeasure: ['advanced school math', 'sequences only', 'large-scale precise computation', 'formula memorization'],
    itemFamilies: ['ratio-scaling', 'proportional-comparison', 'magnitude-estimation', 'relative-quantity', 'arithmetic-model', 'quantitative-transform', 'resource-balance'],
    difficultyModel: ['relation depth', 'representation conversion', 'irrelevant numbers', 'estimation precision', 'reverse inference', 'number of resource constraints'],
  },
  {
    id: 'language',
    construct: 'Understanding semantics, conditions, reference and relational structure under controlled vocabulary.',
    measures: ['verbal relations', 'semantic inference', 'logical language comprehension', 'ambiguity resolution', 'analogy', 'conditional reasoning', 'instruction comprehension'],
    shouldNotMeasure: ['obscure vocabulary size', 'cultural allusions', 'all items as syllogisms', 'reading speed'],
    itemFamilies: ['verbal-relation', 'semantic-inference', 'ambiguity-resolution', 'verbal-analogy', 'conditional-language', 'instruction-comprehension', 'quantifier-scope'],
    difficultyModel: ['condition nesting', 'negation scope', 'number of referent candidates', 'relation abstraction', 'distracting information', 'rule switching'],
  },
  {
    id: 'attention',
    construct: 'Maintaining target rules amid competing stimuli and suppressing irrelevant responses.',
    measures: ['selective attention', 'sustained attention', 'response inhibition', 'target detection', 'interference resistance', 'rule switching'],
    shouldNotMeasure: ['mere Unicode counting', 'complex reasoning', 'color vision as a prerequisite', 'memorizing long sequences'],
    itemFamilies: ['selective-search', 'sustained-target', 'response-inhibition', 'flanker-interference', 'rule-switching', 'conjunction-detection', 'go-no-go'],
    difficultyModel: ['target rarity', 'distractor similarity', 'number of rule switches', 'inhibition frequency', 'stimulus density', 'duration'],
  },
  {
    id: 'speed',
    construct: 'Fast and accurate processing in low-reasoning, clearly-ruled tasks.',
    measures: ['symbol matching', 'same-different judgment', 'visual comparison', 'rapid classification', 'code verification'],
    shouldNotMeasure: ['multi-step reasoning', 'complex computation', 'knowledge recall', 'unreasonably extreme time limits'],
    itemFamilies: ['symbol-matching', 'rapid-same-different', 'visual-comparison', 'rapid-classification', 'visual-code-match', 'feature-scan'],
    difficultyModel: ['item count', 'visual similarity', 'target frequency', 'rule consistency', 'allowed time'],
  },
  {
    id: 'causality',
    construct: 'Distinguishing correlation from causation and judging causal claims with interventions, counterfactuals and evidence structure.',
    measures: ['confound identification', 'intervention reasoning', 'necessary and sufficient', 'counterfactual', 'causal graph intuition', 'evidence strength'],
    shouldNotMeasure: ['only memorizing the "control variables" slogan', 'domain trivia', 'statistical formulas', 'moral judgments'],
    itemFamilies: ['confound-detection', 'intervention-reasoning', 'necessary-sufficient', 'counterfactual', 'causal-graph', 'evidence-strength', 'alternative-explanation'],
    difficultyModel: ['number of variables', 'number of paths', 'counterfactual depth', 'evidence conflict', 'necessary-sufficient conversion', 'confound concealment'],
  },
  {
    id: 'planning',
    construct: 'Constructing and revising multi-step action plans under dependency, resource and competition constraints.',
    measures: ['dependency planning', 'constraint satisfaction', 'resource planning', 'multi-step sequencing', 'goal decomposition', 'replanning'],
    shouldNotMeasure: ['topological sorting only', 'domain expertise', 'unbounded search', 'pure arithmetic optimization'],
    itemFamilies: ['dependency-planning', 'constraint-planning', 'resource-planning', 'multi-step-sequencing', 'goal-decomposition', 'replanning', 'schedule-repair'],
    difficultyModel: ['number of competition constraints', 'resource types', 'plan depth', 'dead-end similarity', 'environment changes', 'sub-goal interactions'],
  },
  {
    id: 'transfer',
    construct: 'Identifying the shared deep structure of superficially different tasks and transferring applicable strategies along with their boundaries.',
    measures: ['structural analogy', 'strategy transfer', 'rule transfer', 'relational mapping', 'near transfer', 'far transfer', 'applicability boundary'],
    shouldNotMeasure: ['mainly doing multiplication rules', 'copying old answers', 'matching identical words only', 'domain knowledge'],
    itemFamilies: ['structural-analogy', 'strategy-transfer', 'rule-transfer', 'relational-mapping', 'near-transfer', 'far-transfer', 'boundary-aware-transfer'],
    difficultyModel: ['surface difference', 'shared relation depth', 'strategy rewrite extent', 'boundary conditions', 'distractor analogy similarity'],
  },
];
