/**
 * Emits src/lib/generated/routeGuardData.generated.ts — a lightweight snapshot
 * of the fields the entry chunk needs for route guards and document metadata.
 *
 * routes.tsx / RouteMetadata.tsx used to import the full characters/extraCharacters/stories
 * data files just for validation and <title> strings, which pulled every bio,
 * chapter object and FSIII helper into the eagerly-loaded bundle. Regenerating
 * this snapshot keeps a single source of truth without that cost.
 *
 * Run automatically by the vite plugin in vite.config.ts (build + dev watcher);
 * safe to run manually: node --experimental-strip-types scripts/generate-route-guard-data.ts
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import { characters } from '../src/data/characters.ts';
import { extraCharacters } from '../src/data/extraCharacters.ts';
import { stories } from '../src/data/stories.ts';

const OUTPUT = resolve(import.meta.dirname, '..', 'src', 'lib', 'generated', 'routeGuardData.generated.ts');

interface CharacterLike {
  id: string;
  name: string;
  bio: string;
  title?: string;
  category?: string;
}

const lines: string[] = [
  '// AUTO-GENERATED by scripts/generate-route-guard-data.ts — do not edit by hand.',
  '// Regenerates on `npm run dev` / `npm run build` whenever src/data changes.',
  '',
  'export interface CharacterGuardEntry {',
  '  id: string;',
  '  name: string;',
  '  bio: string;',
  '  title?: string;',
  '  category?: string;',
  '}',
  '',
  'export interface StoryGuardEntry {',
  '  id: string;',
  '  title: string;',
  '  subtitle?: string;',
  '  chapterCount?: number;',
  '  contentSource?: string;',
  '  chapterTitles: string[];',
  '}',
  '',
  'export const characterGuardData: CharacterGuardEntry[] = [',
];

for (const character of [...characters, ...extraCharacters] as CharacterLike[]) {
  const entry: Record<string, unknown> = {
    id: character.id,
    name: character.name,
    bio: character.bio,
  };
  if ('title' in character && character.title) entry.title = character.title;
  if ('category' in character && character.category) entry.category = character.category;
  lines.push(`  ${JSON.stringify(entry)},`);
}

lines.push('];', '');
lines.push('export const storyGuardData: StoryGuardEntry[] = [');

for (const story of stories) {
  const entry: Record<string, unknown> = {
    id: story.id,
    title: story.title,
    chapterTitles: story.chapters.map((chapter) => chapter.title),
  };
  if (story.subtitle) entry.subtitle = story.subtitle;
  if (story.chapterCount) entry.chapterCount = story.chapterCount;
  if (story.contentSource) entry.contentSource = story.contentSource;
  lines.push(`  ${JSON.stringify(entry)},`);
}

lines.push('];', '');

const next = lines.join('\n');
const previous = (() => {
  try {
    return readFileSync(OUTPUT, 'utf-8');
  } catch {
    return null;
  }
})();

if (previous !== next) {
  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, next, 'utf-8');
  console.log(`route guard data: regenerated (${characters.length + extraCharacters.length} characters, ${stories.length} stories)`);
} else {
  console.log('route guard data: current');
}
